theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
cursorline = true
mouse = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[keys.normal]
y = "yank_to_clipboard"
Y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
